### ISSUE TITLE
UMD build is broken because of prop-types

### ISSUE THREAD

**Issue by PoByBolek** [gpbl/react-day-picker#919] opened 2019-08-08 14:51 UTC
Commit bdc8b3cda0ca63f78c92faabb089d0ba35413705 removed the `transform-react-remove-prop-types` plugin from .babelrc which breaks the UMD build because `prop-types` is still being referenced (but undefined) in the UMD build.

CodeSandbox: https://codesandbox.io/s/ioxwx

**Comment by PoByBolek** [comment] 2019-08-08 15:06
The non-minified build seems to be broken since 7.1.1.

**Comment by artola** [comment] 2019-09-23 10:12
The minified build is broken in v7.3.1 and v7.3.2 while works fine in v7.3.0

It is related to the need to remove the prop-types, in v7.3.0 there was a babel-plugin to do it, but it was removed later in v7.3.1

https://github.com/gpbl/react-day-picker/blob/b08661717076249f1b6c1085174bb1d92aad6b08/.babelrc#L10

@gpbl I would suggest to revert it. Is it ok for you?

https://github.com/gpbl/react-day-picker/commit/bdc8b3cda0ca63f78c92faabb089d0ba35413705#diff-e56633f72ecc521128b3db6586074d2c

**Comment by justinbhopper** [comment] 2020-01-29 05:23
@gpbl Please consider reverting the commit, as suggested above.  I can confirm only v7.3.0 works without error.  The published unpkg versions since then are completely unusable, which is pretty major as new releases go out.

**Comment by sgilligan** [comment] 2020-04-20 09:48
resolved with https://github.com/gpbl/react-day-picker/issues/919 ?

**Comment by gpbl** [comment] 2022-03-26 23:09
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!

**Closed by gpbl** 2022-03-26 23:09 UTC
Labels: Status: PR Welcome, Priority: Low, v7 (maintenance), Type: Build
