### ISSUE TITLE
Proposal - Timepicker

### ISSUE THREAD

**Issue by b2whats** [gpbl/react-day-picker#182] opened 2016-06-16 17:57 UTC
https://www.dropbox.com/s/kuvrbd9gy9jd1xh/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-06-16%2021.08.03.png?dl=0

may be add in calendar timepicker ? if this makes sense I can do PR

**Comment by gpbl** [comment] 2016-06-18 06:46
👋 @b2whats, thanks for the suggestion.
I believe a time picker is out of the scope of this component, and it would work better as a different package. It is easier to develop a time picker component (or use an existing one) and place it near to the day picker, than add this feature directly to it.

**Comment by b2whats** [comment] 2016-06-19 15:43
then we need pass time
https://github.com/gpbl/react-day-picker/blob/master/src/Helpers.js#L46

create PR or you will correct in the next version?

**Comment by gpbl** [comment] 2016-06-19 16:40
The reason there it is set to 12AM is to avoid issues with time zones. I think treating a time picker as a different input should work for most cases, without the need to pass time to the day picker as well. I imagine for example a select element with the times between 0-24.

**Comment by luisrudge** [comment] 2016-06-20 22:59
The problem with always setting 12AM, is that you always reset previously set times.
For example:

> date picker sets `state.date` to `2016-06-20 00:00`
> time picker sets `state.date` to `2016-06-20 15:30`

If I change the date again, it will reset my time:

> date picker sets `state.date` to `2016-06-18 00:00`

I think you just reuse the current time and just change the date. Is that possible?

**Comment by gpbl** [comment] 2016-06-20 23:39
You can use the day picker to set the day, and the time picker to set the time. E.g. 

```
handleDayClick(e, day) {
  this.setState({ day })
}
handleTimeChange(time) {
  this.setState({ time })
}
```

There's no need for `time` to be a `Date` object, but anyway if you want to, then you can get the final date time as

```
getDate() {
  const { day, time } = this.state;
  return new Date(
    day.getFullYear(),
    day.getMonth(),
    day.getDate(),
    time.getHours(),
    time.getMinutes()
  )
};
```

You could otherwise save the date also in a single state by picking the day parts and the time parts.

```js
handleDayClick(e, day) {
  this.setState({
    date: new Date(
      day.getFullYear(),
      day.getMonth(),
      day.getDate(),
      this.state.date.getHours(),
      this.state.date.getMinutes()
  });
}
handleTimeChange(time) {
  this.setState({
    date: new Date(
      this.state.date.getFullYear(),
      this.state.date.getMonth(),
      this.state.date.getDate(),
      time.getHours(),
      time.getMinutes()
  });
}
```

Wouldn't these solutions work for you?

**Comment by luisrudge** [comment] 2016-06-21 00:45
Yeah, I understand we have workarounds for this issue.. But this issue only happens because you're always setting the time.

**Comment by gpbl** [comment] 2016-06-21 08:20
@luisrudge I see thanks for the feedback. To change this behavior we must first have more tests with the day picker working with different timezones. We have been hit by timezones in JS Date object several times (search this repo) and yet the problem is not [really resolved](https://github.com/gpbl/react-day-picker/issues/130) 😓

**Comment by gpbl** [comment] 2016-09-18 18:01
I'm closing this as [we won't](https://github.com/gpbl/react-day-picker/issues/182#issuecomment-226925834) implement a time-picker. 

For the time issue, please keep subscribed to #130 if you need more updates about it – thanks!

**Closed by gpbl** 2016-09-18 18:01 UTC
Labels: discussion
