### ISSUE TITLE
bug(v8) Doesn't work server-side

### ISSUE THREAD

**Issue by nfantone** [gpbl/react-day-picker#1060] opened 2020-09-15 13:40 UTC
**Is your feature request related to a problem? Please describe.**
Latest v8 version (`8.0.0-alpha.45`, as of the moment of this writing) does not support SSR. Library cannot be loaded within frameworks such as Next.js.

> Incidentally, this **does not happen** on `^7.4.8`.

**Describe the solution you'd like**
Library should not depend on `window` existing on load. The Webpack bundle for `index.js` relies on `window` being there as the global root.

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("date-fns"), require("react"));
	else if(typeof define === 'function' && define.amd)
		define(["date-fns", "react"], factory);
	else if(typeof exports === 'object')
		exports["DayPicker"] = factory(require("date-fns"), require("react"));
	else
		root["DayPicker"] = factory(root["DateFns"], root["React"]);
})(window, function(__WEBPACK_EXTERNAL_MODULE__259__, __WEBPACK_EXTERNAL_MODULE__698__) { // <--- HERE
```

**Describe alternatives you've considered**
You could conditionally load the library if running on the browser by means of `require`.

```js
const { DayPicker } = isBrowser() ? require('react-day-picker') : { DayPicker: () => <div /> };
```

While the above works, it leads to its own set of problems. It would be nice for `react-day-picker` to "just work" regardless of the running environment.

**Comment by maxgfr** [comment] 2020-10-05 10:50
+1

**Comment by gpbl** [comment] 2021-02-10 01:17
Hey thanks for the bug report! I believe the latest Webpack fixes this issue, as in the latest build from master I don't see that `window` anymore.

```diff
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("react"), require("date-fns"));
	else if(typeof define === 'function' && define.amd)
		define(["react", "date-fns"], factory);
	else if(typeof exports === 'object')
		exports["DayPicker"] = factory(require("react"), require("date-fns"));
	else
		root["DayPicker"] = factory(root["React"], root["DateFns"]);
- })(window, function(__WEBPACK_EXTERNAL_MODULE__259__, __WEBPACK_EXTERNAL_MODULE__698__) { // <--- HERE
+ })(self, function(__WEBPACK_EXTERNAL_MODULE__698__, __WEBPACK_EXTERNAL_MODULE__259__) {
return /******/ (() => { // webpackBootstrap
```

Closing this as it looks resolved – please reopen if it does not (beta.1 is close to be published on npm).

**Comment by austinhale** [comment] 2021-02-21 07:51
Pretty sure there is still an issue here. I was playing around with adding this to a Nextjs project and almost immediately ran into the following error with a super simple example.

![image](https://user-images.githubusercontent.com/6180399/108618790-f1bc6b00-73ee-11eb-86d2-aa05ad0a3c8c.png)

**Comment by gpbl** [comment] 2021-02-21 14:54
@austinhale thanks for writing back! I am confused since the website seems to render to HTML: https://react-day-picker-next.netlify.app/basics/customization (view source). Probably I'm missing something.

Also node _should not_ require from the `lib` directory but from the `dist` dir – which probably is causing your server to using the browser's global. 

Before we were doing it by setting `module` in package.json ([webpack docs](https://webpack.js.org/guides/author-libraries/#final-steps)) but who knows was changed in between. 

So I changed package.json in b1cbcd0badb192ed02e31a8a22f669d98bedc0c4 but
I'm not familiar with NextJS – is there a way to easily reproduce this?

**Comment by gpbl** [comment] 2021-03-09 16:08
Not sure the SSR verdemosion is using the right version: in v8 the lib/index.js is compiled by Typescript and is ES modules:

https://unpkg.com/react-day-picker@8.0.0-beta.18/lib/index.js

**Comment by henrikbak** [comment] 2021-03-10 18:32
The version used in the example should be 8.0.0-beta.18. It can easily be changed to another version if you need it: https://codesandbox.io/s/awesome-taussig-0t6e5?file=/package.json

**Comment by gpbl** [comment] 2021-03-13 23:55
OK thanks, I could fix it by changing how we export commonjs in #1172:
https://codesandbox.io/s/quizzical-sun-m9fey

Please try if it fixes your case too:

```
npm install react-day-picker@v8.0.0-beta.24
```

Thanks for your time and feedback!

**Closed by gpbl** 2021-03-13 23:55 UTC
Labels: Priority: High, Status: In Progress, Type: Bug

**Comment by gpbl** [comment] 2021-03-14 00:00
(do you have a suggestion – how would you test these built files?)
