### ISSUE TITLE
DayPickerInput is not tab accessible

### ISSUE THREAD

**Issue by PatchOnKnee** [gpbl/react-day-picker#811] opened 2018-10-04 06:26 UTC
DayPickerInput is not tab accessible however the normal DayPicker is. Is there any recommendations for accessibility to be WCAG 2.0 compliant?

You can see this behaviour in the default sandbox: https://codesandbox.io/s/XDAE3x0W8

**Comment by ntanguay** [comment] 2019-09-05 20:31
Seems this is a duplicate of #783

**Closed** 2021-02-10 02:51 UTC
Labels: duplicate
