### ISSUE TITLE
Flickering when moving mouse diagonally between days

### ISSUE THREAD

**Issue by antiwebbite** [gpbl/react-day-picker#610] opened 2018-01-16 19:36 UTC
Hey Guys,

I was wondering if anyone has an idea on how to fix the issue where the mouse and hover states flicker when moving the mouse diagonally between days?

Video: https://screencast-o-matic.com/watch/cFVDqOoDev

I've noticed that even if you force the cursor to pointer on DayPicker-Body, the issue still occurs when the cursor crosses those diagonal edges.

I've repro'd on the official examples as well.

Mac OS X 10.13.2
Chrome 63.0.3239.132

Thanks!

**Comment by gpbl** [comment] 2018-02-23 22:51
Did you make it? Maybe are the rounded corners? I'm closing this if you find the cause feel free to share thanks!

**Closed by gpbl** 2018-02-23 22:51 UTC

**Comment by antiwebbite** [comment] 2018-02-27 20:04
You are correct that changing the border-radius on the hover state from 50% to 0 makes the issue not occur.

I don't know how to fix it for use with a circular hover state, but for anyone where it doesn't matter, changing the border-radius to 3px on this element fixed it for me:

```
.DayPicker:not(.DayPicker--interactionDisabled) .DayPicker-Day:not(.DayPicker-Day--disabled):not(.DayPicker-Day--selected):not(.DayPicker-Day--outside):hover {
    border-radius: 3px;
}
```

**Comment by sv3k** [comment] 2018-05-24 09:36
Maybe it's worth to fix this issue in default react-day-picker styles.

**Comment by gpbl** [comment] 2018-05-24 12:09
@sv3k yeah would you mind to open a PR (provided that it works) thanks!
