### ISSUE TITLE
Remove CSS file dependency

### ISSUE THREAD

**Issue by frandsaw** [gpbl/react-day-picker#209] opened 2016-09-15 09:17 UTC
**Edit:** Rename the prop's attribute

## API proposal
- A new prop `styles` which accepts styles object

### Default styles example
```js
import DayPicker from 'react-day-picker';
import standardStyles from 'react-day-picker/styles/standard';

function MyComponent() {
  return (
    <div>
      <DayPicker styles={standardStyles} />
    </div>
  );
}
```

### Custom styles example
```js
import DayPicker from 'react-day-picker';
import standardStyles from 'react-day-picker/styles/standard';
import { isToday } from './myDateUtils';
import { datePickerMonth } from './my-css-module.css';

const customStyles = Object.assign({}, standardStyles, {
  month: datePickerMonth,
  weekdays: {
    display: 'table-header-group',
    color: 'blue'
  },
  day: day => {
    const style = {
       display: 'table-cell',
       padding: '.5rem',
       border: '1px solid #eaecec',
       textAlign: 'center',
       cursor: 'pointer',
       verticalAlign: 'middle'
    };

    if (isToday(day) {
      return Object.assign(style, { fontWeight: 'bold' });
    }

    return style;
  }
});

function MyComponent() {
  return (
    <div>
      <DayPicker styles={customStyles} />
    </div>
  );
}
```

### Styles
Each style's value can be either a string or an object. It should satisfy both CSS Modules and inline styles. Also, you can pass a modifier function to dynamically update styles (I bet there is a better solution, though).

### Pros
- Instead of external CSS file, you would import regular JS file. It should make easier integration for non-webpack setups
- Inline styles and CSS modules in one place

### Cons
- You have to import styles (including default styles) manually in each module 

What do you think? I will be happy to contribute if you like the idea.

**Comment by gpbl** [comment] 2016-09-15 12:35
Hi @frandsaw thanks for your suggestion! 

I'm not sure what do you mean for "template" – as it seems you mean the style/css class of the HTML elements. Anyway: the next major version will include some API changes that should help to define the style in a more declarative way! Stay tuned :)

**Comment by frandsaw** [comment] 2016-09-15 12:44
Hey @gpbl!

Maybe I screwed up a bit with naming, but you got it right.
The main idea is to remove styles from the core and make it fully controllable through props (but give an option to include basic styles from an external module if needed).
Looking forward for changes 👍

**Comment by frandsaw** [comment] 2016-09-17 12:59
I've changed the title and the description of the issue to make it more clear and correct.

**Comment by gpbl** [comment] 2016-09-18 17:58
Well we are not going to remove the CSS file dependency anyway, as it's not a dependency 😄 
I believe this is more a dupe of #170 and #73.

**Comment by frandsaw** [comment] 2016-09-19 04:15
My main issue is predefined class names. Currently there is no way I can use my own. It would be nice if I could use CSS module class names for every component's layer. But it's fine if it doesn't match with your component's vision :)

You can close this issue then.

**Comment by gpbl** [comment] 2016-09-25 07:14
@frandsaw CSS modules class names are coming, I just need first to review some API. Thanks for your patience!

**Closed by gpbl** 2016-09-25 07:14 UTC
Labels: discussion

**Comment by trevordmiller** [comment] 2019-04-01 22:20
@gpbl Is the .css file import still required? I would prefer to use declarative CSS-in-JS library or inline styles if possible so I don't need to bundle .css. It seems all of the examples still import `import 'react-day-picker/lib/style.css';`
