### ISSUE TITLE
Datepicker Allows Selection of Ranges with Disabled Days in Between

### ISSUE THREAD

**Issue by leonardoparisii** [gpbl/react-day-picker#2035] opened 2024-01-23 22:06 UTC
**Issue Description:**

During the date range selection, it's currently possible to select ranges that include disabled days in between. This behavior is not intended and needs to be addressed to ensure a more accurate and user-friendly date selection experience.

**Expected Behavior:**

The datepicker should restrict users from selecting date ranges that include disabled dates in between. Users should only be able to select continuous date ranges without any disabled days interrupting the selection.

**Comment by gpbl** [comment] 2024-01-26 09:17
This is a duplicate of https://github.com/gpbl/react-day-picker/issues/1885, check the page to see a workaround. We will fix this in the next major version.

**Closed by gpbl** 2024-01-26 09:17 UTC
