### ISSUE TITLE
DayPickerInput does not have disabledDays functionality

### ISSUE THREAD

**Issue by rcavezza** [gpbl/react-day-picker#554] opened 2017-11-17 18:26 UTC
`disabledDays` functionality is allows in `DayPicker`, but not `DayPickerInput`. I took a look at the source and I would guess that the `disabledDays` functionality should be in `DayPickerInput` - maybe there's a bug? I was able to reproduce in codesandbox.

Around line 158 of DayPickerInput.js makes me think the functionality should exist...
```
        var modifiersObj = _extends({
          disabled: dayPickerProps.disabledDays,
          selected: dayPickerProps.selectedDays
        }, dayPickerProps.modifiers);
```

Below is my code snippet I put in codesandbox - I was able to reproduce the issue there. 

```
import React from "react";
import ReactDOM from "react-dom";

import DayPicker from "react-day-picker";
import DayPickerInput from "react-day-picker/DayPickerInput";

import "react-day-picker/lib/style.css";

function Example() {
  const disabledDays = {
    daysOfWeek: [0, 6],
  };

  return (
    <div>
      <h3>DayPicker</h3>
      <DayPicker selectedDays={new Date()} disabledDays={disabledDays} />

      <h3>DayPickerInput</h3>
      <DayPickerInput placeholder="DD/MM/YYYY" format="DD/MM/YYYY" disabledDays={disabledDays} />
    </div>
  );
}

ReactDOM.render(<Example />, document.getElementById("root"));
```

<img width="368" alt="screen shot 2017-11-17 at 1 26 52 pm" src="https://user-images.githubusercontent.com/310231/32962592-0a3bd6e8-cb9b-11e7-9c7c-432692fecdc4.png">

**Comment by gpbl** [comment] 2017-11-17 18:29
Yup! It will be fixed with the next release: https://github.com/gpbl/react-day-picker/pull/531

**Comment by rcavezza** [comment] 2017-11-17 18:37
@gpbl Thank you so much! I'm going to close this in a few minutes. Do you happen to know when the planned next release is?

**Comment by gpbl** [comment] 2017-11-17 22:37
It's [pending](https://github.com/gpbl/react-day-picker/milestone/11). In the next few days 🙏

**Closed by gpbl** 2017-11-17 22:37 UTC

**Comment by gpbl** [comment] 2017-11-25 21:13
Published in v7 😊

**Comment by ajbeaven** [comment] 2018-08-31 03:56
Has there been a regression here? `disabledDays` works for me with DayPicker but not with DayPickerInput on version 7.2.1.

**Comment by gpbl** [comment] 2018-08-31 04:40
@ajbeaven this example uses `disabledDays`: http://react-day-picker.js.org/examples/input-state

**Comment by ajbeaven** [comment] 2018-08-31 10:00
Ahh missed that it needs to be supplied in a datePickerProps object. I guess the API has changed since this issue was created. Thanks for putting me right :)

**Comment by gpbl** [comment] 2018-08-31 17:14
True! Sorry I missed the original example was wrong :)
