### ISSUE TITLE
DateUtils.isFutureDay(next month day)

### ISSUE THREAD

**Issue by NeonSunlight** [gpbl/react-day-picker#238] opened 2016-12-05 23:23 UTC
Hello!

I found the problem: DateUtils.isFutureDay returns false, when the argument is a date of next month.

P.S. - thx for great component!

**Comment by gpbl** [comment] 2016-12-06 13:14
Hi there! Thanks for the report. Could you provide an example of this behavior ?

**Comment by gpbl** [comment] 2017-02-09 22:03
Closing this as I can't reproduce

**Closed by gpbl** 2017-02-09 22:03 UTC
