### ISSUE TITLE
v7 - Input stealing focus when interacting with caption element

### ISSUE THREAD

**Issue by mattfysh** [gpbl/react-day-picker#599] opened 2018-01-04 02:57 UTC
I have a caption element where I've converted the month and year to dropdowns, so users can quickly move across years/decades as needed.

However, the latest version re-applies focus to the input element if clicking inside the container - which causes the dropdown to briefly open and then immediately close. The offending lines: https://github.com/gpbl/react-day-picker/blob/d1a15afdf04475454db75e1f5ef0feea9d1f76cc/src/DayPickerInput.js#L301-L303

Is there any way to disable this behaviour?

**Comment by gpbl** [comment] 2018-01-09 08:36
We are trying to fix this via https://github.com/gpbl/react-day-picker/pull/598. Basically is the same of https://github.com/gpbl/react-day-picker/issues/579. 

At this point, if that `focus` is giving so many problems (basically in firefox, for which the timeout was introduced), we could add a new `keepFocus` prop [to disable it](https://github.com/gpbl/react-day-picker/pull/598#issuecomment-356215295).

**Comment by gpbl** [comment] 2018-01-09 08:36
Closing as duplicate of #579.

**Closed by gpbl** 2018-01-09 08:36 UTC
